version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: matcha
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: matcha
    ports:
      - 5432:5432
    volumes:
      - postgres_database:/var/lib/postgresql
  app:
    build: .
    restart: always
    ports:
      - 4000:4000
      - 9229:9229
    environment:
      - PORT=4000
      - JWT_SECRET=secret
      - POSTGRES_DSN=postgres://matcha:123456@db:5432/matcha
    volumes:
      - ./src:/home/node/app/src
      - ./logs:/home/node/app/logs

volumes:
  postgres_database:
    external: true
